version: '3'
services:
  product_api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - APIPORT=4000
      - DBHOST=localhost
      - DBPORT=5432
      - DBUSER=postgres
      - DBPASS=postgres1234
      - DBNAME=crud_products

